# Import libraries

In [9]:
import pandas as pd
import numpy as np

# Build dataset
- Plan to have a data with 3 diff types of butters and calculate there daily sale in a shop.
    - Sell count : With random function create an numpy array of size 5,3 num ranging from 1 to 20
    - Prices : Create an numpy array for 3 of types of butters

In [10]:
#selling price of butters random function
np.random.seed(9)
selling_count = np.random.randint(20, size =(5,3))
selling_count

array([[ 1,  8, 17],
       [ 1,  0, 14],
       [10, 10, 12],
       [18,  1,  3],
       [11,  5, 19]], dtype=int32)

# Selling count dataframe
- Rows with days
- Columns with types of butters and there selling count

In [11]:
weekly_sales = pd.DataFrame(selling_count, 
                           index = ["MON","TUES","WED","THRUS","FRI"], #rows
                           columns = ["ALMOND BUTTER", "PEANUT BUTTER", "CASHEW BUTTER"]
                           )
weekly_sales

ALMOND BUTTER  PEANUT BUTTER  CASHEW BUTTER
MON                1              8             17
TUES               1              0             14
WED               10             10             12
THRUS             18              1              3
FRI               11              5             19

In [14]:
prices = np.array([16,12,20])
prices

array([16, 12, 20])

# Prices dataframe
- Row with price 
- Column with 3 types of butter

In [16]:
#price datafram
Butter_prices = pd.DataFrame(prices.reshape(1,3),
                             index = ["Price"],
                             columns = ["ALMOND BUTTER","PEANUT BUTTER","CASHEW BUTTER"]
                            )
Butter_prices

ALMOND BUTTER  PEANUT BUTTER  CASHEW BUTTER
Price             16             12             20

# DOT PRODUCT
- Calculate total sell for a week
- T swaps the rows and columns:
    - Prices matrix = (1,3)
    - selling price=(5,3)
    - if selling_count.T matrix = (3,5)
    - Product = (1,3)*(3,5)

In [19]:
# Implement TOtal in DataFrame
daily_sales = Butter_prices.dot(weekly_sales.T)
daily_sales

MON  TUES  WED  THRUS  FRI
Price  452   296  520    360  616

# Add in a dataframe with new col as TOTAL
- Dot product vales are in row
- .T swpas rows ro column

In [20]:
weekly_sales ["TOTAL"] = daily_sales.T
weekly_sales

ALMOND BUTTER  PEANUT BUTTER  CASHEW BUTTER  TOTAL
MON                1              8             17    452
TUES               1              0             14    296
WED               10             10             12    520
THRUS             18              1              3    360
FRI               11              5             19    616

# SORTING ARRAY
- Create an array with size 5*5 range 1 to 20
  - np.sort - sort an array along rows ascending order
  - np.argsort - returns an array with same number location(index) in original array
  - argmin axis=0/1 - return an array with min number index along x or Y axis
  - argmax axis=0/1 -  return an array with max number index along x or Y axis

In [24]:
np.random.seed(42)
sort_arr = np.random.randint(1,20, size=(5,5))
sort_arr

array([[ 7, 15, 11,  8,  7],
       [19, 11, 11,  4,  8],
       [ 3,  2, 12,  6,  2],
       [ 1, 12, 12, 17, 10],
       [16, 15, 15, 19, 12]], dtype=int32)

In [25]:
arr1  = np.sort(sort_arr)
arr1

array([[ 7,  7,  8, 11, 15],
       [ 4,  8, 11, 11, 19],
       [ 2,  2,  3,  6, 12],
       [ 1, 10, 12, 12, 17],
       [12, 15, 15, 16, 19]], dtype=int32)

In [26]:
arr2 = np.argsort(sort_arr)
arr2

array([[0, 4, 3, 2, 1],
       [3, 4, 1, 2, 0],
       [1, 4, 0, 3, 2],
       [0, 4, 1, 2, 3],
       [4, 1, 2, 0, 3]])

In [28]:
# Col wise min elements indices
arr3 = np.argmin(sort_arr, axis=1)
arr3

array([0, 3, 1, 0, 4])

In [33]:
#Col wise max elements indices
arr4 = np.argmax(sort_arr, axis=1)
arr4

array([1, 0, 2, 3, 3])

In [34]:
sort_arr

array([[ 7, 15, 11,  8,  7],
       [19, 11, 11,  4,  8],
       [ 3,  2, 12,  6,  2],
       [ 1, 12, 12, 17, 10],
       [16, 15, 15, 19, 12]], dtype=int32)

In [35]:
#Row min elements indices
arr5 = np.argmin(sort_arr, axis=0)
arr5

array([3, 2, 0, 1, 2])

In [36]:
#Row wise max elements indices
arr6 = np.argmax(sort_arr, axis=0)
arr6

array([1, 0, 4, 4, 4])